### ISSUE TITLE
Références Doc2Vec, Digital Labor, CD4ML

### ISSUE THREAD

**Issue by SaboniAmine** [SubstraFoundation/referentiel-ds-responsable-confiance#25]
Voici un des articles qui parle de la problématique de Doc2Vec : 
https://www.pnas.org/content/115/16/E3635

Pour être honnête les biais détectés sont générés par les datasets d'entraînement sur lesquels l'algorithme d'embedding s'est entraîné. 
De ma compréhension Word2Vec a créé une méthode d'embedding de mots à partir d'un corpus historique et est ensuite spécialisé sur un corpus lors de son utilisation en industrie ou sur un sujet donné. On a donc 2 phases d'entraînement : une terminée (celle de la construction de l'algo d'embedding) et une qui est réitérée à chaque utilisation différente de Word2Vec.

Le point de l'article est de dire que les biais générés dans la première phase sont assez variés au cours des siècles et qu'il est possible de déduire des informations sur l'époque en observant les constructions algorithmiques faites sur des éléments discriminants ces époques.

Voici la référence du livre d'Antonio Casili que j'étudie actuellement (c'est de la sociologie digitale, et un peu compliqué à lire...) : http://www.seuil.com/ouvrage/en-attendant-les-robots-antonio-a-casilli/9782021401882

Concernant le software craftmanship, voici l'article [CD4ML](https://martinfowler.com/articles/cd4ml.html) qui présente les approches du craft appliqué au ML. Si vous souhaitez pousser dans le craft et la performance logicielle, les conclusions de l'étude State of Devops 2019 ont été publiées dans le livre [Accelerate](https://www.oreilly.com/library/view/accelerate/9781457191435/) et apportent des analyses assez pertinentes.

Je vous joins aussi notre article sur l'aspect 'boîtes noires' que nous présentons en conférence en mars prochain. Les commentaires et critiques sont évidemment les bienvenues, compte tenu du manque de richesse scientifique et de résultats de cet article. 
[Opening the black box of algorithms](https://github.com/SubstraFoundation/referentiel-ds-responsable-confiance/files/4165680/Final_version.pdf)

**Comment by SaboniAmine** [comment]
Pour poursuivre sur l'intérêt de l'interprétabilité, voici un article rédigé par Annabelle Blangero & un collègue data scientist sur la confiance en les utilisateurs : https://blog.octo.com/la-confiance-des-utilisateurs-dans-les-systemes-impliquant-de-lintelligence-artificielle/

**Comment by natct10** [comment]
Super, merci !

**Comment by bowni** [comment]
Merci @SaboniAmine, à lire donc pour tous ceux qui veulent augmenter leur discernement sur ces sujets. Nous allons ajouter certaines de ces références à la liste de lecture (`references.md`), et voir comment en tirer le maximum pour renforcer le référentiel.
J'en profite pour ajouter une référence, [Concrete Problems in AI Safety](https://arxiv.org/abs/1606.06565), sur "_the problem of accidents in machine learning systems, defined as unintended and harmful behavior that may emerge from poor design of real-world AI systems._"

**Comment by bowni** [comment]
> Voici un des articles qui parle de la problématique de Doc2Vec :
> https://www.pnas.org/content/115/16/E3635
> 
> Pour être honnête les biais détectés sont générés par les datasets d'entraînement sur lesquels l'algorithme d'embedding s'est entraîné.
> De ma compréhension Word2Vec a créé une méthode d'embedding de mots à partir d'un corpus historique et est ensuite spécialisé sur un corpus lors de son utilisation en industrie ou sur un sujet donné. On a donc 2 phases d'entraînement : une terminée (celle de la construction de l'algo d'embedding) et une qui est réitérée à chaque utilisation différente de Word2Vec.
> 
> Le point de l'article est de dire que les biais générés dans la première phase sont assez variés au cours des siècles et qu'il est possible de déduire des informations sur l'époque en observant les constructions algorithmiques faites sur des éléments discriminants ces époques.
> 
> Voici la référence du livre d'Antonio Casili que j'étudie actuellement (c'est de la sociologie digitale, et un peu compliqué à lire...) : http://www.seuil.com/ouvrage/en-attendant-les-robots-antonio-a-casilli/9782021401882
> 
> Concernant le software craftmanship, voici l'article [CD4ML](https://martinfowler.com/articles/cd4ml.html) qui présente les approches du craft appliqué au ML. Si vous souhaitez pousser dans le craft et la performance logicielle, les conclusions de l'étude State of Devops 2019 ont été publiées dans le livre [Accelerate](https://www.oreilly.com/library/view/accelerate/9781457191435/) et apportent des analyses assez pertinentes.
> 
> Je vous joins aussi notre article sur l'aspect 'boîtes noires' que nous présentons en conférence en mars prochain. Les commentaires et critiques sont évidemment les bienvenues, compte tenu du manque de richesse scientifique et de résultats de cet article.
> [Opening the black box of algorithms](https://github.com/SubstraFoundation/referentiel-ds-responsable-confiance/files/4165680/Final_version.pdf)

@SaboniAmine votre article "Opening up the black box of algorithms" peut-il être partagé ? Avez-vous une version en ligne (e.g. arXiv ou autre) ?

**Comment by SaboniAmine** [comment]
Nous l'avons publié sur [medium](https://medium.com/@asaboni/opening-the-algorithms-black-box-and-understand-its-outputs-e2363b0a887c).

**Comment by natct10** [comment]
> Nous l'avons publié sur [medium](https://medium.com/@asaboni/opening-the-algorithms-black-box-and-understand-its-outputs-e2363b0a887c).

Oh great, thank you @SaboniAmine !
