### ISSUE TITLE
Reformulation risque RC3-01

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/referentiel-ds-responsable-confiance#3]
Je remplacerai :
_dans le cas d'un incident avec ou dû à un modèle prédictif : pour le sujet concerné, ne pas savoir vers qui se tourner pour demander des comptes_

par :
_dans le cas d'un incident provoqué par un modèle prédictif, ne pas avoir de responsable humain identifié à qui demander des comptes_

**Comment by bowni** [comment]
Merci ! C'est traité
