### ISSUE TITLE
Ajout de référence

### ISSUE THREAD

**Issue by SaboniAmine** [SubstraFoundation/referentiel-ds-responsable-confiance#8]
Voici l'article que je vous ai brièvement présenté de Lê Nguyen Hoang, écrit en 2017 et revu en 2019, pour mieux coller à ses réflexions et à la publication de son livre sur la question [Le fabuleux chantier pour rendre l’intelligence artificielle robustement bénéfique](https://laboutique.edpsciences.fr/produit/1107/9782759824304/Le%20fabuleux%20chantier) :

- [A Roadmap for Robust End-to-End Alignment](https://arxiv.org/pdf/1809.01036.pdf) 

Edit : 
Référence sur les saisies par AWS (semestre par semestre) : https://www.amazon.com/gp/help/customer/display.html?nodeId=GYSDRGWQ2C2CRYEF

Références sur l'embbeding de mots (traduction de mots en vecteur) discriminatoire : 
- [Word embeddings quantify 100 years of gender
and ethnic stereotypes](https://www.pnas.org/content/pnas/115/16/E3635.full.pdf)

- [Christine Basta, Marta R. Costa-juss`a, Noe Casas. Evaluating the Underlying Gender Bias in Contextualized Word Embeddings, 2018](https://arxiv.org/pdf/1904.08783.pdf)

**Comment by bowni** [comment]
Merci @SaboniAmine, très précieux ces références. Je les rajoute à ma liste de lecture et essaierai de les inclure d'ici la semaine de rentrée
